import Box from '@mui/material/Box';
import Typography from '@mui/material/Typography';
import Divider from '@mui/material/Divider';

const Home = () => {
  return (
    <Box sx={{ paddingTop: 2 }}>
      <Typography variant='h2' className='glitch' data-text='Code as Art'>
        Code as Art
      </Typography>
      <Typography variant='h5' sx={{ marginTop: 4 }}>
        ArtSource is an open platform for creating and collecting generative art
        and smart contract art on the Flow blockchain.
      </Typography>
      <Typography variant='h5' sx={{ marginTop: 4 }}>
        You can treat the code itself as art, not just the images generated by
        the code.
      </Typography>
      <Box sx={{ marginTop: 6 }}>
        <img
          src={'/img/concept.png'}
          alt={'concept'}
          width={600}
          style={{
            boxShadow:
              'rgba(67, 71, 85, 0.27) 0px 0px 0.25em, rgba(90, 125, 188, 0.05) 0px 0.25em 1em',
          }}
        />
      </Box>
      <Divider sx={{ margin: '32px 0' }} />
    </Box>
  );
};

export default Home;
